[package]
name = "noted2"
version = "2.0.0"
edition = "2023"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version="4.4.11", features=["cargo"]}

